# .github/workflows/test.yml
name: Run tests

on:
  push:
    branches:
      - master
      - '*.x'
  pull_request:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3]

    name: PHP ${{ matrix.php }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: task_management_system

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, json
        coverage: none

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-interaction --no-progress
      working-directory: ./task_management_system

    - name: Copy environment file
      run: cp .env.example .env
      working-directory: ./task_management_system

    - name: Generate app key
      run: php artisan key:generate
      working-directory: ./task_management_system

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: task_management_system/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install npm dependencies
      run: npm install

    - name: Build assets
      run: npm run build
      working-directory: ./task_management_system

    - name: Create SQLite database
      run: |
        touch database/database.sqlite
        php artisan migrate --env=testing --database=sqlite --path=database/migrations
      working-directory: ./task_management_system

    - name: Run tests
      run: vendor/bin/phpunit
      working-directory: ./task_management_system
